# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6433bd10a582e13dff068208344f02974f2544dc97411d0f35ac588baefdb5c6928b81432cee30985011154e8ac619459a864ff7705d5b9e196449c7e2abc6d2

test:
  secret_key_base: 9dd195bc83eaf606a5c9e88dc9c4a4bc3244c7508f46a9839edcb1f13ed90f64da14262e4f7d75937cc24db46975d414c62ba861a0327d81391a17756ee15969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
